import{a as b,S,i as w}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const E="22291580-fa60bbd7949edc60de7cbcd1e",q="https://pixabay.com/api/";async function h(e,t=1){return await b.get(q,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:"15"}}).then(i=>i.data.hits).catch(i=>{throw new Error(i)})}function g(e){return e.map(({webformatURL:t,largeImageURL:i,tags:l,likes:r,views:o,comments:s,downloads:L})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${t}" alt="${l}" />
      </a>
      <ul class="info-cards">
        <li class="info-card"><h3>Likes</h3><p>${r}</p></li>
        <li class="info-card"><h3>Views</h3><p>${o}</p></li>
        <li class="info-card"><h3>Comments</h3><p>${s}</p></li>
        <li class="info-card"><h3>Downloads</h3><p>${L}</p></li>
      </ul>
    </li>`).join("")}function m(e,t){e.insertAdjacentHTML("beforeend",t)}function B(e){e.innerHTML=""}function p(){const e=new S(".gallery a");e.on("show.simplelightbox"),e.refresh()}function d(e){w.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:e})}function a(e){e.classList.toggle("hidden")}function v(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}const f=document.querySelector(".form"),u=document.querySelector(".gallery"),x=document.querySelector(".loadMore"),n=document.querySelector(".Loadmore").children;let c="",y=1;f.addEventListener("submit",async e=>{if(e.preventDefault(),c=e.target["search-text"].value.trim(),!!c){B(u),a(n[0]);try{const t=await h(c);t.length?(y=1,m(u,g(t)),p()):d("Sorry, there are no images matching your search query.")}catch{d("Error fetching images, please try again.")}finally{a(n[0]),a(n[1]),f.reset()}}});x.addEventListener("click",async()=>{a(n[0]),a(n[1]);try{const e=await h(c,++y);e.length?(m(u,g(e)),p()):d("You've reached the end of search results.")}catch{d("Error loading more images.")}finally{v(),a(n[0]),a(n[1])}});
//# sourceMappingURL=index.js.map
