import{a as E,S as q,i as B}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const v="22291580-fa60bbd7949edc60de7cbcd1e",$="https://pixabay.com/api/";async function y(e,t=1){return await E.get($,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:"15"}}).then(s=>s.data).catch(s=>{throw new Error(s)})}function L(e){return e.map(({webformatURL:t,largeImageURL:s,tags:n,likes:r,views:o,comments:a,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${t}" alt="${n}" />
      </a>
      <ul class="info-cards">
        <li class="info-card"><h3>Likes</h3><p>${r}</p></li>
        <li class="info-card"><h3>Views</h3><p>${o}</p></li>
        <li class="info-card"><h3>Comments</h3><p>${a}</p></li>
        <li class="info-card"><h3>Downloads</h3><p>${w}</p></li>
      </ul>
    </li>`).join("")}function b(e,t){e.insertAdjacentHTML("beforeend",t)}function x(e){e.innerHTML=""}let f=null;function S(){f?f.refresh():f=new q(".gallery a")}function h(e){B.error({backgroundColor:"#EF4040",messageColor:"#FAFAFB",theme:"dark",progressBarColor:"#B51B1B",maxWidth:"432",messageSize:"16",position:"topRight",message:e})}function d(e){e.classList.toggle("hidden")}function M(){const e=document.querySelector(".gallery-item");if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}const p=document.querySelector(".form"),g=document.querySelector(".gallery"),i=document.querySelector(".loadMore"),u=document.querySelector(".Loadmore").children;let l="",c=1,m=0;p.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target["search-text"].value.trim(),!!l){x(g),d(u[0]);try{const t=await y(l);console.log(t);const s=t.hits;m=t.totalHits,s.length?(c=1,b(g,L(s)),S(),m>15?i.classList.remove("hidden"):i.classList.add("hidden")):(h("Sorry, there are no images matching your search query."),i.classList.add("hidden"))}catch{h("Error fetching images, please try again.")}finally{d(u[0]),p.reset()}}});i.addEventListener("click",async()=>{d(u[0]);try{c++;const t=(await y(l,c)).hits;t.length?(b(g,L(t)),S(),c*15>=m&&i.classList.add("hidden")):i.classList.add("hidden")}catch{h("Error loading more images.")}finally{M(),d(u[0])}});
//# sourceMappingURL=index.js.map
